name: package
on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: workflow loaded
        run: echo "✅ package workflow parsed"

      - uses: actions/checkout@v4

      - name: lint workflow (actionlint)
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check

      - id: meta
        name: lower-case repo
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dev tools
        run: pip install ruff black yamllint

      - name: run ruff
        run: ruff check .

      - name: run black --check
        run: black --check .

      - name: yamllint
        run: yamllint .

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }}
          push: false
          load: true

      - name: unit tests
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} \
            python -m pytest -q

      - name: smoke test
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} /bin/true

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.ref_name }}
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
          push: true
          load: false
