name: package
on:
  push:
    tags:
      - '*'                          # any lightweight or annotated tag

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: workflow loaded
        run: echo "✅ package workflow parsed"

      - uses: actions/checkout@v4

      - id: meta
        name: lower-case repo for GHCR
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1. build once for tests (push=false, load=true)
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }}
          push: false
          load: true

      # 2. run unit tests inside that image
      - name: unit tests
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} \
            python -m pytest -q

      # 3. smoke test: container starts and exits 0 in CI mode
      - name: smoke test
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} /bin/true

      # 4. final build & push version tag + latest
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.ref_name }}
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
          push: true
          load: false
