---
name: package
'on':
  push:
    tags:
      - '*'                            # run on every tag

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install ruff black
      - run: ruff check .
      - run: black --check .

  publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: workflow parsed
        run: echo "✅ package workflow loaded"

      - uses: actions/checkout@v4

      - id: meta
        name: lowercase repo
        run: |
          repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "repo=$repo" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: shellcheck entrypoint
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'entrypoint.sh'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args: INSTALL_DEV_DEPS=true
          tags: "${{ format('ghcr.io/{0}:{1}', steps.meta.outputs.repo, github.sha) }}"
          push: false
          load: true

      - name: unit tests
        if: always()
        run: |
          docker run --rm \
            -e CI_MODE=true \
            -e DEVICE=/dev/null \
            -e BAUDRATE=9600 \
            -e TELEGRAM_BOT_TOKEN=dummy \
            -e TELEGRAM_CHAT_ID=dummy \
            -e GAMMU_SPOOL_PATH=/tmp/gammu \
            -e GAMMU_CONFIG_PATH=/tmp/smsdrc \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} \
            python -m pytest -q -k "not test_detect_modem"

      - name: smoke test with compose
        run: |
          IMAGE="ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }}"
          export IMAGE
          docker compose -f compose.ci.yml up -d
          sleep 20
          docker compose -f compose.ci.yml ps
          docker compose -f compose.ci.yml logs smsgateway
          docker compose -f compose.ci.yml down

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ format('ghcr.io/{0}:{1}', steps.meta.outputs.repo, github.ref_name) }}
            ${{ format('ghcr.io/{0}:latest', steps.meta.outputs.repo) }}
          push: true
