name: package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare meta
        id: meta
        run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }}
          push: false
          load: true

        - name: Unit tests inside container
          run: |
            docker run --rm \
              -e CI_MODE=true \
              ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} \
              python -m pytest -q

        - name: Smoke test container
          run: |
            IMAGE="ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }}"
            docker run --rm -e CI_MODE=true "$IMAGE" /bin/true

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.ref_name }}
            ghcr.io/${{ steps.meta.outputs.repo }}:latest
          push: true
          load: false

