---
name: package
'on':
  push:
    tags:
      - '*'                            # run on every tag

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: workflow parsed
        run: echo "✅ package workflow loaded"

      - uses: actions/checkout@v4

      - id: meta
        name: lowercase repo
        run: |
          repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "repo=$repo" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: shellcheck entrypoint
        uses: ludeeus/action-shellcheck@v1
        with:
          check_together: 'entrypoint.sh'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: "${{ format('ghcr.io/{0}:{1}', steps.meta.outputs.repo, github.sha) }}"
          push: false
          load: true

      - name: unit tests
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} \
            python -m pytest -q

      - name: smoke test
        run: |
          docker run --rm -e CI_MODE=true \
            ghcr.io/${{ steps.meta.outputs.repo }}:${{ github.sha }} /bin/true

      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ format('ghcr.io/{0}:{1}', steps.meta.outputs.repo, github.ref_name) }}
            ${{ format('ghcr.io/{0}:latest', steps.meta.outputs.repo) }}
          push: true
          load: false
